name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
# references:
#   - dev
categories:
  - title: "🚀 Features"
    labels:
      - "Type: Feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "Type: Bug Fix"
  - title: "🧰 Maintenance"
    label:
      - "Type: Maintenance"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "Release: Major"
  minor:
    labels:
      - "Release: Minor"
  patch:
    labels:
      - "Release: Patch"
  default: patch
exclude-labels:
  - "skip-changelog"
template: |
  ## Changelog
  $CHANGES
  🙏 A big thank you to all the contributors to this release:
  $CONTRIBUTORS
