name-template: "v$NEXT_PATCH_VERSION 🌈"
tag-template: "v$NEXT_PATCH_VERSION"
# references:
#   - dev
categories:
  - title: "🚀 Features"
    labels:
      - "Feature"
      - "Enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "Bug"
      - "Bugfix"
      - "fix" 
  - title: "🧰 Maintenance"
    label: "Maintenance"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "Release: Major"
  minor:
    labels:
      - "Release: Minor"
  patch:
    labels:
      - "Release: Patch"
  default: patch
exclude-labels:
  - "skip-changelog"
template: |
  ## Changelog
  $CHANGES
  🙏 A big thank you to all the contributors to this release:
  $CONTRIBUTORS
  $PREVIOUS_TAG	
