version: '2'

checks:
  file-lines:
    enabled: false

  method-lines:
    enabled: false

  similar-code:
    enabled: false

plugins:
  eslint:
    enabled: true
    channel: 'eslint-7'
    config: .eslintrc.json
