name: Lingui extract
on:
  pull_request:
    branches:
      - "dev"
jobs:
  # extract any new translatable string
  # and commit if there are new ones
  extract:
    name: lingui-extract
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: set user
      env:
        GITHUB_PACKAGES_AUTH_TOKEN: ${{ secrets.GH_PKG_AUTH_TOKEN }}
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    # use node module caching
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: install packages
      run: yarn install --immutable

    - name: lingui-extract
      run: |
        (cd packages/files-ui && yarn extract --clean)
        git add packages/files-ui/src/locales/*
        if git commit -m "lingui extract"; then git push; else echo 'exiting successfully without commit'; fi