name: PR Labeler
on: pull_request

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
